### ISSUE TITLE
Недоработки сайта

### ISSUE THREAD

**Issue by mglknFSD** [dywork/toxin#27]
1. Открытие дропдауна срабатывает не всегда (в отличие от анимации нажатия). И сама анимация выглядит немного заторможено.

https://user-images.githubusercontent.com/75975369/118285925-a0e27d00-b4da-11eb-8cef-0bd1c6fc758d.mp4

2. Bordered кнопка немного не соответвует дизайну

Как у тебя 

https://user-images.githubusercontent.com/75975369/118286653-57def880-b4db-11eb-8433-c3c69e4a3c7f.mp4

Как должно быть

![should](https://user-images.githubusercontent.com/75975369/118286680-5f9e9d00-b4db-11eb-926f-a51462bbaf6f.jpg)

**Comment by mglknFSD** [comment]
3. Во время перехода на другую страницу я вижу странные "артефакты"  (Firefox)

https://user-images.githubusercontent.com/75975369/118287463-24509e00-b4dc-11eb-9bd2-5a7e7448c68b.mp4

**Comment by mglknFSD** [comment]
4. Дата рождения в форме должна быть "маской". Т е у пользователя должна быть возможность ввести только цифры (ничего больше - точки между ними ставятся автоматически)

**Comment by mglknFSD** [comment]
5. Accessibility - если починишь, будет + в карму и опыт.

Если табать по форме то табы игнорируют checkbox и radio button. Человек без мышки не сможет эти части формы отредактировать.


https://user-images.githubusercontent.com/75975369/118288991-91b0fe80-b4dd-11eb-9e93-16b716751c2b.mp4

**Comment by mglknFSD** [comment]
6. Галерея при разных разрешениях искажает картинки внутри себя. Выглядит это ужасно. Представь ты заходишь на сайт с мобильного телефона и видишь фото номера словно из кривого зеркала... Давай сделаем так что бы фотографии сохраняли свои пропорции.


https://user-images.githubusercontent.com/75975369/118290030-a346d600-b4de-11eb-9697-915ab820464b.mp4

**Comment by mglknFSD** [comment]
7. Футер для маленьких дисплеев не соответствует дизайну

Сверху для больших, снизу для маленьких.

![small display](https://user-images.githubusercontent.com/75975369/118290269-ea34cb80-b4de-11eb-9a26-2be05cd5bcfa.jpg)

**Comment by mglknFSD** [comment]
8. Не работает форма бронирования. Ожидается, что при изменении даты будет пересчитываться итоговая сумма.

https://user-images.githubusercontent.com/75975369/118290668-5a435180-b4df-11eb-8890-0f9a0f11831f.mp4

**Comment by mglknFSD** [comment]
9. Мне кажется тут не хватает отступа.

![margin](https://user-images.githubusercontent.com/75975369/118291177-f53c2b80-b4df-11eb-9829-7aa0c8ebd2c8.jpg)

**Comment by mglknFSD** [comment]
10. На ipad страница поиска отелей выглядит не очень хорошо - слишком большие промежутки между тайлами номеров.
В идеале, все компоненты должны быть резиновыми, и уметь заполнять доступное пространство.

![ipad](https://user-images.githubusercontent.com/75975369/118291673-87443400-b4e0-11eb-9acf-830f81920693.jpg)

**Comment by dywork** [comment]
![image](https://user-images.githubusercontent.com/17548109/123422745-12ccdc80-d5d8-11eb-9d79-557e4c0a3353.png)
@mglknFSD не очевидно, что это дизайн именно ховера кнопки. Осветление выглядит как disabled

**Comment by mglknFSD** [comment]
> ![image](https://user-images.githubusercontent.com/17548109/123422745-12ccdc80-d5d8-11eb-9d79-557e4c0a3353.png)
> @mglknFSD не очевидно, что это дизайн именно ховера кнопки. Осветление выглядит как disabled. Но даже если дизайнер имел ввиду, что это именно ховер эффект, то я готов спорить, что осветлять такие цвета для ховера хорошая идея, т.к. рейтинг доступности контраста таких цветов текста и бордера в нормальном состоянии кнопки и так 2.24 (тогда как рекомендуемое значение 4.5 - https://web.dev/color-and-contrast-accessibility/?utm_source=devtools). Низкий рейтинг контрастности может мешать пользоваться нашими интерфейсами, например в светлый день когда светит солнце и мы не видим текст.
> 
> ![image](https://user-images.githubusercontent.com/17548109/123423777-6986e600-d5d9-11eb-98b1-b1234651a26f.png)

Есть что-то не очевидно - то необходимо спрашивать.

**Comment by dywork** [comment]
> > ![image](https://user-images.githubusercontent.com/17548109/123422745-12ccdc80-d5d8-11eb-9d79-557e4c0a3353.png)
> > @mglknFSD не очевидно, что это дизайн именно ховера кнопки. Осветление выглядит как disabled. Но даже если дизайнер имел ввиду, что это именно ховер эффект, то я готов спорить, что осветлять такие цвета для ховера хорошая идея, т.к. рейтинг доступности контраста таких цветов текста и бордера в нормальном состоянии кнопки и так 2.24 (тогда как рекомендуемое значение 4.5 - https://web.dev/color-and-contrast-accessibility/?utm_source=devtools). Низкий рейтинг контрастности может мешать пользоваться нашими интерфейсами, например в светлый день когда светит солнце и мы не видим текст.
> > ![image](https://user-images.githubusercontent.com/17548109/123423777-6986e600-d5d9-11eb-98b1-b1234651a26f.png)
> 
> Есть что-то не очевидно - то необходимо спрашивать.

Направил через Виктора вопрос дизайнеру, насчет осветления кнопки и ссылки при ховере.

**Comment by mglknFSD** [comment]
Иконки съехали.

![icons](https://user-images.githubusercontent.com/75975369/123506066-fcbc2c00-d66a-11eb-856d-b13370e5d886.jpg)

**Comment by dywork** [comment]
> 1. Accessibility - если починишь, будет + в карму и опыт.
> 
> Если табать по форме то табы игнорируют checkbox и radio button. Человек без мышки не сможет эти части формы отредактировать.
> 
>  2021-05-14-17-52-34.mp4

добавил фокус этим элементам:

![image](https://user-images.githubusercontent.com/17548109/123507841-326e0e80-d685-11eb-83c7-678142962671.png)

А момент переключения инпутов в checked мне обрабатывать js'ом? Или можно как html+css сделать?

**Comment by dywork** [comment]
> 1. Футер для маленьких дисплеев не соответствует дизайну
> 
> Сверху для больших, снизу для маленьких.
> 
> ![small display](https://user-images.githubusercontent.com/75975369/118290269-ea34cb80-b4de-11eb-9a26-2be05cd5bcfa.jpg)

Футер который предлагается в дизайне для планш. и моб. версий имеет некоторые проблемы:

1. Лишает пользователя информативного меню по сайту.
2. Лишает пользователя возможности подписки по email.

Не против если останется мой вариант футера? На командном этапе заказчик был не против отойти от дизайна в этом вопросе.

**Comment by mglknFSD** [comment]
> 
> 
> > 1. Футер для маленьких дисплеев не соответствует дизайну
> > 
> > Сверху для больших, снизу для маленьких.
> > ![small display](https://user-images.githubusercontent.com/75975369/118290269-ea34cb80-b4de-11eb-9a26-2be05cd5bcfa.jpg)
> 
> Футер который предлагается в дизайне для планш. и моб. версий имеет некоторые проблемы:
> 
>     1. Лишает пользователя информативного меню по сайту(навигация, о нас, служба поддержки)
> 
>     2. Лишает пользователя возможности подписки по email.
> 
> 
> Не против если останется мой вариант футера? На командном этапе заказчик был не против отойти от дизайна в этом вопросе.

Вообще такие вопросы обговариваются с заказчиком предварительно, но в данном случае это не критично, можешь оставить как есть.

**Comment by mglknFSD** [comment]
Accessibility.

Ты поправил в форме регистрации возможность "протапать" все элементы управления, но для checkbox и radio-button в твоей реализации это бесполезно. Возможность взаимодействия только с помощью клавиатуры дается в случае если другие средства взаимодействия отсутствуют. checkbox должен менять свой статус при нажатии пробела, а radio-button при нажатии стрелок влево/вправо.

**Comment by dywork** [comment]
> Accessibility.
> 
> Ты поправил в форме регистрации возможность "протапать" все элементы управления, но для checkbox и radio-button в твоей реализации это бесполезно. Возможность взаимодействия только с помощью клавиатуры дается в случае если другие средства взаимодействия отсутствуют. checkbox должен менять свой статус при нажатии пробела, а radio-button при нажатии стрелок влево/вправо.

да я там выше спросил https://github.com/dywork/toxin/issues/27#issuecomment-868970901, jsом сделать или может вдруг есть другой вариант.

**Comment by dywork** [comment]
> 1. На ipad страница поиска отелей выглядит не очень хорошо - слишком большие промежутки между тайлами номеров.
>    В идеале, все компоненты должны быть резиновыми, и уметь заполнять доступное пространство.
> 
> ![ipad](https://user-images.githubusercontent.com/75975369/118291673-87443400-b4e0-11eb-9acf-830f81920693.jpg)

space-around подойдет?

![image](https://user-images.githubusercontent.com/17548109/123542026-c95bc900-d760-11eb-9589-e98e379c8bca.png)

**Comment by mglknFSD** [comment]
> 
> 
> > Accessibility.
> > Ты поправил в форме регистрации возможность "протапать" все элементы управления, но для checkbox и radio-button в твоей реализации это бесполезно. Возможность взаимодействия только с помощью клавиатуры дается в случае если другие средства взаимодействия отсутствуют. checkbox должен менять свой статус при нажатии пробела, а radio-button при нажатии стрелок влево/вправо.
> 
> ~да я там выше спросил(под скрином) [#27 (comment)](https://github.com/dywork/toxin/issues/27#issuecomment-868970901), jsом сделать или может вдруг есть другой вариант?~
> 
> добавил js.

Извини, пропустил коммент. Это так работает по умолчанию, и если делать по хорошему - надо просто написать так что бы эту механику не испортить. Но как напишешь - так напишешь, это больше для твоего развития и понимания доступности.

**Comment by dywork** [comment]
> > 1. На ipad страница поиска отелей выглядит не очень хорошо - слишком большие промежутки между тайлами номеров.
> >    В идеале, все компоненты должны быть резиновыми, и уметь заполнять доступное пространство.
> > 
> > ![ipad](https://user-images.githubusercontent.com/75975369/118291673-87443400-b4e0-11eb-9acf-830f81920693.jpg)
> 
> @mglknFSD, space-around подойдет?
> 
> ![image](https://user-images.githubusercontent.com/17548109/123542026-c95bc900-d760-11eb-9589-e98e379c8bca.png)

сделал space-around.

**Comment by mglknFSD** [comment]
> > > 1. На ipad страница поиска отелей выглядит не очень хорошо - слишком большие промежутки между тайлами номеров.
> > >    В идеале, все компоненты должны быть резиновыми, и уметь заполнять доступное пространство.
> > > 
> > > ![ipad](https://user-images.githubusercontent.com/75975369/118291673-87443400-b4e0-11eb-9acf-830f81920693.jpg)
> > 
> > 
> > @mglknFSD, space-around подойдет?
> > ![image](https://user-images.githubusercontent.com/17548109/123542026-c95bc900-d760-11eb-9589-e98e379c8bca.png)
> 
> сделал space-around.

Так лучше

**Comment by mglknFSD** [comment]
Что-то все поломалось.

https://user-images.githubusercontent.com/75975369/126862093-ef588c98-b274-49b2-bb34-97f09f461c7d.mp4

**Comment by mglknFSD** [comment]
В панели слева указано что это hover эффект, сейчас он реализован другой.

![hover](https://user-images.githubusercontent.com/75975369/126868967-fd5c9f68-5cbb-4a5a-b4fe-83073a52fae4.jpg)

**Comment by dywork** [comment]
> Что-то все поломалось.
> 
>  11-07-26.mp4

не получается баг отловить.
chrome: Версия 92.0.4515.107

https://user-images.githubusercontent.com/17548109/127768534-0ad70cbe-37ca-4882-b9d7-bd5b0c4d3274.mp4

firefox: Версия 90.0.2

https://user-images.githubusercontent.com/17548109/127768499-595cb409-44a3-4f56-a9a7-6ce91c8292e1.mp4

**Comment by mglknFSD** [comment]
Состояние hover кнопки не соответсвует дизайну.

![button](https://user-images.githubusercontent.com/75975369/128540567-ab2d54f3-105d-4ee9-8ba0-d9f95164b834.jpg)
