### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by mglknFSD** [dywork/toxin#28]
[Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.

![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)

**Comment by mglknFSD** [comment]
Лучше использовать декструктуризацию в параметрах.

![destructuring](https://user-images.githubusercontent.com/75975369/118295212-43532e00-b4e4-11eb-8788-d8d9ebb124ea.jpg)

**Comment by mglknFSD** [comment]
Это очевидная опечатка, ожидается что ты ее исправишь.

![zzz](https://user-images.githubusercontent.com/75975369/118295544-a644c500-b4e4-11eb-8c90-298ab5ec57af.jpg)

**Comment by mglknFSD** [comment]
Думаю что подобный код эффективнее переписать на циклы.

![for](https://user-images.githubusercontent.com/75975369/118295800-ea37ca00-b4e4-11eb-931c-7af6263dac05.jpg)

**Comment by mglknFSD** [comment]
С какой целью ты приравниваешь пустой объект в качестве значения по умолчанию?

![p](https://user-images.githubusercontent.com/75975369/118296874-1c95f700-b4e6-11eb-869e-b9cdfed16c1f.jpg)

**Comment by mglknFSD** [comment]
Названия некоторых классов не очень семантичны. Я могу понять wrap - т е это обертка для чего-то. Но что означает span? Span это пробел, промежуток. Если ты хотел указать на тег `span` то это не очень хорошая практика. 

![semantic](https://user-images.githubusercontent.com/75975369/118297418-c83f4700-b4e6-11eb-818e-0d1bff9587d7.jpg)

**Comment by mglknFSD** [comment]
Date input, хорошо бы оформить в виде отдельного компонента, который принимал бы конфигурацию, и рисовал 2 поля или одно в зависимости от это конфигурации.

![date input](https://user-images.githubusercontent.com/75975369/118297900-6cc18900-b4e7-11eb-9a51-e4d55d80c5bc.jpg)

**Comment by mglknFSD** [comment]
Форматирование.
У нас по стандарту принят стандарт airbnb в котором максимальная длинна строк 80 символов. Давай придерживаться этого стандарта для всех файлов.

![f](https://user-images.githubusercontent.com/75975369/118298463-2a4c7c00-b4e8-11eb-9891-046fb84ec198.jpg)

**Comment by dywork** [comment]
> Лучше использовать декструктуризацию в параметрах.
> 
> ![destructuring](https://user-images.githubusercontent.com/75975369/118295212-43532e00-b4e4-11eb-8788-d8d9ebb124ea.jpg)

В компонентах button и total-card не получается деструктурировать в параметрах, т.к. длина строки превышает 80 символов, а сделать формат такого типа:

![image](https://user-images.githubusercontent.com/17548109/123074700-fb9fba80-d430-11eb-8d9a-60764b65c0c7.png)

в pug вызывает ошибку:

![image](https://user-images.githubusercontent.com/17548109/123074823-16722f00-d431-11eb-9e87-19074c2b81e4.png)


долго пробовал различные комбинации отступов и пробелов, ошибка та же самая :(

**Comment by dywork** [comment]
> [Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.
> 
> ![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)

Добавил классы инлайновым элементам к которым применяю стили. Остальные инлайновые элементы без моих стилей оставил без классов т.к. считаю это излишним +
> Но можно для инлайновых элементов, если есть четкое понимание зачем.

**Comment by mglknFSD** [comment]
> > [Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.
> > ![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)
> 
> Добавил классы инлайновым элементам к которым применяю стили. Остальные инлайновые элементы без моих стилей оставил без классов т.к. считаю это излишним +
> 
> > Но можно для инлайновых элементов, если есть четкое понимание зачем.

Ну хотелось бы услышать аргументы "четкого понимания зачем".

**Comment by dywork** [comment]
> > > [Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.
> > > ![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)
> > 
> > 
> > Добавил классы инлайновым элементам к которым применяю стили. Остальные инлайновые элементы без моих стилей оставил без классов т.к. считаю это излишним +
> > > Но можно для инлайновых элементов, если есть четкое понимание зачем.
> 
> Ну хотелось бы услышать аргументы "четкого понимания зачем".

Затем, что этому элементу мне не нужно применять никаких стилей, зачем мне класс на инлайновом элементе, если я ничего не делаю с этим классом?

**Comment by mglknFSD** [comment]
> > > > [Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.
> > > > ![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)
> > > 
> > > 
> > > Добавил классы инлайновым элементам к которым применяю стили. Остальные инлайновые элементы без моих стилей оставил без классов т.к. считаю это излишним +
> > > > Но можно для инлайновых элементов, если есть четкое понимание зачем.
> > 
> > 
> > Ну хотелось бы услышать аргументы "четкого понимания зачем".
> 
> Затем, что этому элементу мне не нужно применять никаких стилей, зачем мне класс на инлайновом элементе, если я ничего не делаю с этим 

Т е в твоем блоке этот элемент твоего блока никак не стилизуется, а где он стилизуется?

**Comment by dywork** [comment]
> > > > > [Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.
> > > > > ![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)
> > > > 
> > > > 
> > > > Добавил классы инлайновым элементам к которым применяю стили. Остальные инлайновые элементы без моих стилей оставил без классов т.к. считаю это излишним +
> > > > > Но можно для инлайновых элементов, если есть четкое понимание зачем.
> > > 
> > > 
> > > Ну хотелось бы услышать аргументы "четкого понимания зачем".
> > 
> > 
> > Затем, что этому элементу мне не нужно применять никаких стилей, зачем мне класс на инлайновом элементе, если я ничего не делаю с этим
> 
> Т е в твоем блоке этот элемент твоего блока никак не стилизуется, а где он стилизуется?

это всего 1 тэг, как раз <p></p> в auth-card. Там достаточно стилей его родителя который задает расположение. Цвет и размер он наследует от родителя.

**Comment by mglknFSD** [comment]
> 
> 
> > > > > > [Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.
> > > > > > ![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)
> > > > > 
> > > > > 
> > > > > Добавил классы инлайновым элементам к которым применяю стили. Остальные инлайновые элементы без моих стилей оставил без классов т.к. считаю это излишним +
> > > > > > Но можно для инлайновых элементов, если есть четкое понимание зачем.
> > > > 
> > > > 
> > > > Ну хотелось бы услышать аргументы "четкого понимания зачем".
> > > 
> > > 
> > > Затем, что этому элементу мне не нужно применять никаких стилей, зачем мне класс на инлайновом элементе, если я ничего не делаю с этим
> > 
> > 
> > Т е в твоем блоке этот элемент твоего блока никак не стилизуется, а где он стилизуется?
> 
> это всего 1 тэг, как раз (p) в auth-card. Там достаточно стилей его родителя который задает расположение. Цвет и размер он наследует от родителя.

Проблема заключается в следующем. Если где-то выше я напишу что-то вроде

```css
p {
  color: red;
  font-size: 20px;
}
```

то это будет переопределять стили для этого параграфа, и верстка поедет. И ищи потом почему она поехала. Блок по БЭМ подразумевается как независимая единица, поэтому в этой методологии сознательно уходят от каскада, что бы он не зависел от внешних стилей. 

Оговорка `Но можно для инлайновых элементов, если есть четкое понимание зачем.` касается когда тебе важен этот каскад влияния, и тебе без него сложно обойтись.

**Comment by dywork** [comment]
> > > > > > > [Все теги идут только с классами](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) Просмотри весь проект.
> > > > > > > ![p](https://user-images.githubusercontent.com/75975369/118295022-0ab35480-b4e4-11eb-8b9b-ca59cb1b8234.jpg)
> > > > > > 
> > > > > > 
> > > > > > Добавил классы инлайновым элементам к которым применяю стили. Остальные инлайновые элементы без моих стилей оставил без классов т.к. считаю это излишним +
> > > > > > > Но можно для инлайновых элементов, если есть четкое понимание зачем.
> > > > > 
> > > > > 
> > > > > Ну хотелось бы услышать аргументы "четкого понимания зачем".
> > > > 
> > > > 
> > > > Затем, что этому элементу мне не нужно применять никаких стилей, зачем мне класс на инлайновом элементе, если я ничего не делаю с этим
> > > 
> > > 
> > > Т е в твоем блоке этот элемент твоего блока никак не стилизуется, а где он стилизуется?
> > 
> > 
> > это всего 1 тэг, как раз (p) в auth-card. Там достаточно стилей его родителя который задает расположение. Цвет и размер он наследует от родителя.
> 
> Проблема заключается в следующем. Если где-то выше я напишу что-то вроде
> 
> ```css
> p {
>   color: red;
>   font-size: 20px;
> }
> ```
> 
> то это будет переопределять стили для этого параграфа, и верстка поедет. И ищи потом почему она поехала. Блок по БЭМ подразумевается как независимая единица, поэтому в этой методологии сознательно уходят от каскада, что бы он не зависел от внешних стилей.
> 
> Оговорка `Но можно для инлайновых элементов, если есть четкое понимание зачем.` касается когда тебе важен этот каскад влияния, и тебе без него сложно обойтись.

В данном конкретном случае, такое правило 

> ```css
> p {
>   color: red;
>   font-size: 20px;
> }
> ```

Переопределит стили не только этого p без класса, но и остальных p с классами где явно не указаны font-size и color. А это почти все p которые используют каскад для цвета, размера, семейства шрифтов, длины строки и т.д. 
"Каскад — зло". Это не правило, это просто рекомендация и я уверен, что в каскаде внутри блока для инлайновых элементов нет ничего страшного. Иначе нам нужно было бы для каждого инлайнового элемента указывать явно, font-family, font-size, color, line-height, font-weight, text-align и т.д. сколько фантазия тебе позволит, даже display придется явно указать ведь, кто-то может написать  

> ```css
> p {
>   display: inline; 
> }
> ```

Я уверен, что никто не хочет писать этот лишний код(могу ошибаться), но даже при первом ревью был момент когда мне порекомендовали удалить одно из свойств у инлайного элемента, ведь оно и так наследуется и зачем дублировать. 

К тому же к счастью ты не можешь написать правило 
> ```css
> p {
>   color: red;
>   font-size: 20px;
> }
> ```

т.к. есть стандарт запрещающий такое делать и если верстка поедет или что-то сломается, проблема именно в этом правиле, а не в том, что мы не предусмотрели такой кейс.

**Comment by mglknFSD** [comment]
Я посовещался к коллегами - главная причина наличия класса, все таки в читаемости. `p` без класса не имеет явной семантики в контексте этого блока. Стилизовать его не обязательно, но придумать имя, все же, надо.

**Comment by dywork** [comment]
> Я посовещался к коллегами - главная причина наличия класса, все таки в читаемости. `p` без класса не имеет явной семантики в контексте этого блока. Стилизовать его не обязательно, но придумать имя, все же, надо.

👍 сделаю
