### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by mglknFSD** [dywork/toxin#31]
[В проекте обязательно должен быть favicon.ico, подключаемый на всех страницах.](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#3.2)

**Comment by dywork** [comment]
@mglknFSD поставил с нуля проект, открыл в чистом браузере с очищенным кешем, на всех страницах есть фавиконки и на локальном (localhost:8080) и на gh pages.

**Comment by mglknFSD** [comment]
Issue не про то что favicon не отображается, а про то что должна быть возможность подключать ее на каждой странице (возможно мы захотим что бы она на всех страницах была разной)
