### ISSUE TITLE
css

### ISSUE THREAD

**Issue by mglknFSD** [dywork/toxin#32]
1. Глобальные стили запрещены. (разрешены только для html,body и * для box-sizing)

![global style](https://user-images.githubusercontent.com/75975369/118389519-034e9100-b633-11eb-8fdd-9ae5394f9901.jpg)

2. Font family лучше то же вынести в переменные.

![font family](https://user-images.githubusercontent.com/75975369/118389627-63ddce00-b633-11eb-9876-5834c7bdad10.jpg)

3. Магические числа. Почему именно такие значения?

![mag](https://user-images.githubusercontent.com/75975369/118389687-a43d4c00-b633-11eb-9397-95dc9b870c3b.jpg)

4. normalize.css лучше не копипастить в проект а установить через npm

![normalize css](https://user-images.githubusercontent.com/75975369/118389714-d51d8100-b633-11eb-81a0-ace1b08cc1bc.jpg)

**Comment by mglknFSD** [comment]
5. Градиенты то же можно вынести в переменную (они повторяются)

**Comment by mglknFSD** [comment]
6. Тут, чтобы не повоторятся, можно использовать переменную и интерполяцию.

![var](https://user-images.githubusercontent.com/75975369/118389854-aa7ff800-b634-11eb-8113-bae303fb7373.jpg)

**Comment by mglknFSD** [comment]
7. Закоментированный код нужно удалять.

![commented](https://user-images.githubusercontent.com/75975369/118389916-03e82700-b635-11eb-901d-3ce32a50a9e7.jpg)

**Comment by mglknFSD** [comment]
8. [Именование модификаторов](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.1)

Этот и другие issues смотри по всему проекту

![naming](https://user-images.githubusercontent.com/75975369/118389999-70fbbc80-b635-11eb-85f8-0634aea6c751.jpg)

**Comment by mglknFSD** [comment]
9. Селекторы по тегам запрещены.

![tag selectors](https://user-images.githubusercontent.com/75975369/118390156-45c59d00-b636-11eb-9e6d-a8b56d0937c8.jpg)

**Comment by dywork** [comment]
> 1. Селекторы по тегам запрещены.
> 
> ![tag selectors](https://user-images.githubusercontent.com/75975369/118390156-45c59d00-b636-11eb-9e6d-a8b56d0937c8.jpg)

Добавил классы для инлайновых элементов со своими стилями, но я не нашел такого пункта в стандартах компании, был бы благодарен если бы помог найти :)

**Comment by mglknFSD** [comment]
> > 1. Селекторы по тегам запрещены.
> > 
> > ![tag selectors](https://user-images.githubusercontent.com/75975369/118390156-45c59d00-b636-11eb-9e6d-a8b56d0937c8.jpg)
> 
> Добавил классы для инлайновых элементов со своими стилями, но я не нашел такого пункта в стандартах компании, был бы благодарен если бы помог найти :)

Селекторы по тегам запрещены по БЭМ.

**Comment by dywork** [comment]
![image](https://user-images.githubusercontent.com/17548109/123413691-7fda7500-d5cc-11eb-8bd1-9f08a86ddc60.png)
@mglknFSD, потому что 80.5556% в моем контейнере на 1440px ширине экрана идеально входить по PP.
с 80.5556%:
![image](https://user-images.githubusercontent.com/17548109/123414046-d647b380-d5cc-11eb-82d0-1be1a454eeee.png)
c 80%:
![image](https://user-images.githubusercontent.com/17548109/123414110-eb244700-d5cc-11eb-97a6-cb15ac959167.png)

до 1300px оставил просто 90%

**Comment by dywork** [comment]
> 1. Тут, чтобы не повоторятся, можно использовать переменную и интерполяцию.
> 
> ![var](https://user-images.githubusercontent.com/75975369/118389854-aa7ff800-b634-11eb-8113-bae303fb7373.jpg)

Продублирую вопрос из тг. Не совсем понял, что нужно сделать?

**Comment by mglknFSD** [comment]
> 
> 
> > 1. Тут, чтобы не повоторятся, можно использовать переменную и интерполяцию.
> > 
> > ![var](https://user-images.githubusercontent.com/75975369/118389854-aa7ff800-b634-11eb-8113-bae303fb7373.jpg)
> 
> Продублирую вопрос из тг. Не совсем понял, что нужно сделать?

Использую scss можно писать такие конструкуции:

```scss

.some {
  $block: &;

  &__element-1 {
    &:focus + #{$block}__element-2 {
      ...
    }
  }
}
```

Сохраняем в переменную текущий класс блока и используем ее внутри блока. Таким образом если нам нужно будет переименовать блок, нам не нужно будет смотреть код внутри блока что бы ничего не забыть.

**Comment by mglknFSD** [comment]
[Именование модификаторов](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.1) не исправлено. 

![modificator](https://user-images.githubusercontent.com/75975369/126862296-e6f500c3-c7a6-4fed-b6b7-a9e66daa3a4a.jpg)

Если пройти по ссылке выше и почитать то основная идея что `блок__компонент_модификатор` должны быть синтаксически и семантически корректными словосочетаниями.

Например 

`button_disabled` - звучит хорошо - отмененная кнопка, звучит как модификатор, т к мы к кнопке добавляем состояние disabled

`button_variant-text` - звучит плохо, не звучит как модификатор, скорее как компонент.

`button_with-variant-text` - звучт лучше. Т е вот у нас кнопка и мы к ней добавляем (with) модификатор ( добавляем ей стили для текстового варианта)

**Comment by mglknFSD** [comment]
1-н блок = 1-н класс

![block](https://user-images.githubusercontent.com/75975369/128541278-64156a1f-23f9-481d-926a-779b86554170.jpg)

**Comment by mglknFSD** [comment]
Почему у datepicker нет index.js?

![datepicker](https://user-images.githubusercontent.com/75975369/128542938-a8b7a87c-188c-478e-928e-8374591e7edc.jpg)
