### ISSUE TITLE
Js

### ISSUE THREAD

**Issue by mglknFSD** [dywork/toxin#37]
1. Огроомный конструктор.

![constructor](https://user-images.githubusercontent.com/75975369/123538744-f303f880-d73e-11eb-82ff-8a019f1f0739.jpg)

**Comment by mglknFSD** [comment]
2. Предикаты содержащие более одного условия должны быть вынесены.
3. Функция обработчик для forEach очень большая, ее нужно вынести.

![js](https://user-images.githubusercontent.com/75975369/123538891-93f2b380-d73f-11eb-8a7c-85b8dd80465e.jpg)

**Comment by mglknFSD** [comment]
4. [Правила именования обработчиков событий. ](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#3.3)

![handler](https://user-images.githubusercontent.com/75975369/123539052-812cae80-d740-11eb-8fce-7f132fc302ec.jpg)

**Comment by mglknFSD** [comment]
5. Коды лучше вынести в отдельную константу, что бы улучшить читаемость.

![cod](https://user-images.githubusercontent.com/75975369/123539125-d072df00-d740-11eb-82d7-924e35b65f43.jpg)

**Comment by mglknFSD** [comment]
6. Вложеные if-ы сложно читать и поддерживать. Исправь пожалуйста.

![nested if](https://user-images.githubusercontent.com/75975369/123539221-49723680-d741-11eb-83f3-d2038dbc1da9.jpg)

**Comment by mglknFSD** [comment]
7. Пытался понять что делает эта функция исходя из названия - и ее смысл ускользнул от меня. declOfNum. `decl` это от `declaration`? Т е она объявляет что-то? Число какое-то? Вроде нет. Возвращает title исходя из магических `cases`. Нужно переписать эту и им подобные функции что бы их было легко читать.

![awk_fun](https://user-images.githubusercontent.com/75975369/123539312-c8676f00-d741-11eb-8d9d-698973d3499d.jpg)

**Comment by dywork** [comment]
@mglknFSD if (arrivalDate && departureDate)  это не одно условие?

**Comment by mglknFSD** [comment]
> 
> 
> @mglknFSD if (arrivalDate && departureDate) это не одно условие?

Это 2 условия

**Comment by dywork** [comment]
> > @mglknFSD if (arrivalDate && departureDate) это не одно условие?
> 
> Это 2 условия

Имеет ли смысл выносить такое в переменную? Вроде читаемо?

**Comment by mglknFSD** [comment]
> 
> 
> > > @mglknFSD if (arrivalDate && departureDate) это не одно условие?
> > 
> > 
> > Это 2 условия
> 
> Имеет ли смысл выносить такое в переменную? Вроде читаемо?

Лично у меня претензий нет, но правила есть правила.

**Comment by dywork** [comment]
> > > > @mglknFSD if (arrivalDate && departureDate) это не одно условие?
> > > 
> > > 
> > > Это 2 условия
> > 
> > 
> > Имеет ли смысл выносить такое в переменную? Вроде читаемо?
> 
> Лично у меня претензий нет, но правила есть правила.

Все таки мне кажется, что условие одно, проверяет он 2 переменные да, что и та и та существует, но условие же 1?) Что то и то существует, по другому никак. Я поинтересовался у Данила (sodiqit), что он думает о вынесении такого в переменную, ему тоже кажется это излишним. Можешь поинтересоваться у коллег нужно ли вынести в переменную?

**Comment by mglknFSD** [comment]
> никак

`Все проверки содержащие более одного условия должны быть вынесены.` 

`f (arrivalDate && departureDate)` эти два условия можно расписать вот так `arrivalDate === true` и `departureDate === true`. Т е предполагается что эти 2 переменные являются булевыми и мы делаем неявное сравнение на true (если не учитывать неявное приведение типов, для него есть отдельное правило). Получается что у нас есть 2 условия которые мы объединяем оператором `&&`.

**Comment by dywork** [comment]
> > Все таки мне кажется, что условие одно, проверяет он 2 переменные да, что и та и та существует, но условие же 1?) Что то и то существует, по другому никак. Я поинтересовался у Данила (sodiqit), что он думает о вынесении такого в переменную, ему тоже кажется это излишним. Можешь поинтересоваться у коллег нужно ли вынести в переменную?
> 
> `Все проверки содержащие более одного условия должны быть вынесены.`
> 
> `f (arrivalDate && departureDate)` эти два условия можно расписать вот так `arrivalDate === true` и `departureDate === true`. Т е предполагается что эти 2 переменные являются булевыми и мы делаем неявное сравнение на true (если не учитывать неявное приведение типов, для него есть отдельное правило). Получается что у нас есть 2 условия которые мы объединяем оператором `&&`.

ок

**Comment by dywork** [comment]
> 1. Пытался понять что делает эта функция исходя из названия - и ее смысл ускользнул от меня. declOfNum. `decl` это от `declaration`? Т е она объявляет что-то? Число какое-то? Вроде нет. Возвращает title исходя из магических `cases`. Нужно переписать эту и им подобные функции что бы их было легко читать.
> 
> ![awk_fun](https://user-images.githubusercontent.com/75975369/123539312-c8676f00-d741-11eb-8d9d-698973d3499d.jpg)

это склонение окончаний
https://qna.habr.com/q/676240
https://gist.github.com/realmyst/1262561

есть ещё такое конечно:
```
function declOfNum(n, titles) {
  return titles[n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2];
}
```
отсюда http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms
Мне её на что переписать?)

**Comment by mglknFSD** [comment]
> это склонение окончаний
> https://gist.github.com/YozhEzhi/9ae6c83841e74f4710c3372f93400d35
> https://qna.habr.com/q/676240
> https://gist.github.com/realmyst/1262561
> 
> есть ещё такое конечно:
> 
> ```
> function declOfNum(n, titles) {
>   return titles[n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2];
> }
> ```
> 
> отсюда http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms
> 
> Мне её на что переписать?)

Для таких вещей лучше использовать библиотеки (в реальном проекте дак точно), но если решил написать сам назови функцию что бы не возникало двусмысленности. Если делаешь копипасту, я бы указал источник в комментариях. Но лучше используй библиотеку.

**Comment by dywork** [comment]
@mglknFSD, немного затрудняюсь с вынесением в переменные вот этих условий из **src/components/date-picker/components/CalendarTableView.js**:


```
if (isLastWeekDaySaturday && lastDayCurrentMonth >= 30) {
  numberRow = 6;
}

if (isLastWeekDayFriday && lastDayCurrentMonth === 31) {
  numberRow = 6;
}

if (isLastWeekDaySunday && isLeapYear) {
  numberRow = 4;
}
```

Если выносить их в переменные получается что-то типа:
isLastWeekDayFriday && lastDayCurrentMonth === 31: **isLastWeekDayFridayAndLastDayCurrentMonthEqual31**
isLastWeekDaySunday && isLeapYear: **isLastWeekDaySundayAndIsLeapYear**

Мне кажется без вынесения в переменные нагляднее. Не подскажешь, как можно здесь поступить?

**Comment by mglknFSD** [comment]
> 
> 
> @mglknFSD, немного затрудняюсь с вынесением в переменные вот этих условий из **src/components/date-picker/components/CalendarTableView.js**:
> 
> ```
> if (isLastWeekDaySaturday && lastDayCurrentMonth >= 30) {
>   numberRow = 6;
> }
> 
> if (isLastWeekDayFriday && lastDayCurrentMonth === 31) {
>   numberRow = 6;
> }
> 
> if (isLastWeekDaySunday && isLeapYear) {
>   numberRow = 4;
> }
> ```
> 
> Если выносить их в переменные получается что-то типа:
> isLastWeekDayFriday && lastDayCurrentMonth === 31: **isLastWeekDayFridayAndLastDayCurrentMonthEqual31**
> isLastWeekDaySunday && isLeapYear: **isLastWeekDaySundayAndIsLeapYear**
> 
> Мне кажется без вынесения в переменные нагляднее. Не подскажешь, как можно здесь поступить?

Вынесение составных предикатов делается для лучшей читаемости кода. 

Смысл в том что сама константа предикат должна не двусмысленно говорить нам что тут проверяется, и нам не приходилось это "додумывать", пытаясь в голове сопоставить эти предикаты. Иногда это избыточно, но правила есть правила. И это все делается не просто "что бы было" или "так красивее". А что бы код был единообразным, и любой член команды читал его как свой собственный.

Я бы это отрефакторил как-то так

```js

//  и тут поинт в том что я точно не знаю что ты проверяешь, 
//  и мне приходится догадываться, придумывая имя для переменной.... 
const isFridayLastDayInMonth = isLastWeekDaySaturday && lastDayCurrentMonth >= 30;

if (isFridayLastDayInMonth) {
  numberRow = 6;
}
```

**Comment by mglknFSD** [comment]
Вложеный if. Данную конструкцию довольно легко порефакторить сделав код более "плоским" что облегчит его чтение и поддержку.

![nested if](https://user-images.githubusercontent.com/75975369/126861091-1c6c958d-b350-4e86-a428-5ac198cd0020.jpg)

**Comment by mglknFSD** [comment]
Довольно большая анонимная функция лучше вынести в метод класса

![callback](https://user-images.githubusercontent.com/75975369/126861186-1f425438-e40b-4e2c-9fc1-66c3db59aa21.jpg)

**Comment by mglknFSD** [comment]
Обработчик не может быть анонимной функцией.

![click](https://user-images.githubusercontent.com/75975369/126861244-3d9c92bc-1c6c-4017-a9d1-4e7bd5a71a9a.jpg)
